### ISSUE TITLE
Make "Pyz" project target customisable

### ISSUE THREAD

**Issue by Chemaclass** [turbine-kreuzberg/spryker-idea-plugin#2]
Use case: you can define an inheritance with another project name on top of Pyz, so you can keep Pyz from the demo shop in order to upgrade it easier, for example, and don't mixup the logic from the demoshop and your company business logic.

In the `ExtendInPyzAction:44` you have hardcoded defined the `Pyz` project name:
```java
String targetPath = project.getBasePath() + "/src/Pyz/" + relativeClassPath;
```
It would be awesome if we could define the project name somehow in the Plugging configuration, while keeping `Pyz` value by default.

**Comment by colons-litzmann** [comment]
+1 To that. Our Project has a folder structure like `project.getBasePath() + "/current/src/Pyz/" + relativeClassPath;` Having a setting for that would be greatly appreciated :)

**Comment by senor-dingdong** [comment]
Good point. We're gonna do this for sure.

**Comment by senor-dingdong** [comment]
we pushed an update. you can specify your PYZ directory now in settings->tools->pyz plugin
can you try it and give feedback?

**Comment by colons-litzmann** [comment]
> we pushed an update (0.3.0). you can specify your PYZ directory now in settings->tools->pyz plugin can you try it and give feedback?

Works perfectly for me now! Thank you very much

**Comment by Chemaclass** [comment]
@senor-dingdong it works pretty awesome. Exactly what I was looking for! Great job 🚀
