### ISSUE TITLE
Zed stub navigation to gateway controller does not work for Spryker vendor classes

### ISSUE THREAD

**Issue by Lkopo** [turbine-kreuzberg/spryker-idea-plugin#4]
**Tested on**: PhpStorm 2022.2.4, Build #PS-222.4459.28
**OS**: Windows 10
**Plugin version**: 0.7.5

----

As for project level, the navigation to Gateway controller methods from Zed stub URL's works perfectly, it does seem to be glitchy for vendor classes. Example in AuthRestApi module in spryker:

![image](https://user-images.githubusercontent.com/6184484/212040583-bf65265a-a57f-4df6-8ad4-18bc2793b401.png)

Same issue I faced on other vendor modules as well. Would be helpful to have it working too, as sometimes code debugging leads to the vendor code as well.

**Comment by senor-dingdong** [comment]
Hi again @Lkopo, thanks for reporting! This is a bug, should be fixed with version 0.7.7.
